name: Docker Image CI

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    
    - name: Pull the Docker image jfrog/router
      run: docker pull releases-docker.jfrog.io/jfrog/router:7.36.1
    - name: tag image 
      run: docker tag $(docker images --filter=reference=releases-docker.jfrog.io/jfrog/router --format "{{.ID}}") ${{ secrets.DOCKER_HUB_USERNAME }}/router:7.36.1

    - name: Pull the Docker image jfrog/insight-scheduler
      run: docker pull releases-docker.jfrog.io/jfrog/insight-scheduler:4.7.9
    - name: tag image 
      run: docker tag $(docker images --filter=reference=releases-docker.jfrog.io/jfrog/insight-scheduler --format "{{.ID}}") ${{ secrets.DOCKER_HUB_USERNAME }}/insight-scheduler:4.7.9
    
    - name: Pull the Docker image jfrog/insight-server
      run: docker pull releases-docker.jfrog.io/jfrog/insight-server:4.7.9
    - name: tag image 
      run: docker tag $(docker images --filter=reference=releases-docker.jfrog.io/jfrog/insight-server --format "{{.ID}}") ${{ secrets.DOCKER_HUB_USERNAME }}/insight-server:4.7.9
  
    - name: Pull the Docker image jfrog/elasticsearch
      run: docker pull releases-docker.jfrog.io/jfrog/elasticsearch-sg:7.16.3
    - name: tag image 
      run: docker tag $(docker images --filter=reference=releases-docker.jfrog.io/jfrog/elasticsearch-sg --format "{{.ID}}") ${{ secrets.DOCKER_HUB_USERNAME }}/elasticsearch-sg:7.16.3

    - name: Pull the Docker image jfrog/postgres
      run: docker pull releases-docker.jfrog.io/postgres:13.4-alpine
    - name: tag image 
      run: docker tag $(docker images --filter=reference=releases-docker.jfrog.io/postgres --format "{{.ID}}") ${{ secrets.DOCKER_HUB_USERNAME }}/postgres:13.4-alpine



      
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_PASS: ${{ secrets.DOCKER_HUB_PASSWD }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASS docker.io
      
    - name: push router
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/router:7.36.1
 
    - name: push insight_scheduler
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/insight-scheduler:4.7.9
    
    - name: push insight_server
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/insight-server:4.7.9
    
    - name: push elasticsearch
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/elasticsearch-sg:7.16.3
    
    - name: push postgres
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/postgres:13.4-alpine

      
      
      
