name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t metrics-server:v0.3.7 . --file metrics-server.Dockerfile
    
    - name: Docker Login
      env:
        DOCKER_USER: 'wearehadock'
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASS

