name: Docker Image CI

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    
    - name: Pull the Docker image cluster-proportional-autoscaler-amd64
      run: docker pull releases-docker.jfrog.io/jfrog/router:7.36.1

    - name: tag image 
      run: docker tag $(docker images --filter=refrence=releases-docker.jfrog.io/jfrog/router --format "{{.ID}}") ${{ secrets.DOCKER_HUB_USERNAME }}/jfrog/router:7.36.1


      
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_PASS: ${{ secrets.DOCKER_HUB_PASSWD }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      
    - name: push controller
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/jfrog/router:7.36.1
 
      
      
      
