name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build the Docker image kube-proxy
      run: docker build -t kube-proxy:v1.18.10 . --file kube-proxy.Dockerfile
    - name: tag image 
      run: docker tag $(docker images --filter=reference=kube-proxy --format "{{.ID}}") wearehadock/kube-proxy:v1.18.10
    
    - name: Build the Docker image metrics-server
      run: docker build -t metrics-server:v0.3.7 . --file metrics-server.Dockerfile
    - name: tag image 
      run: docker tag $(docker images --filter=reference=metrics-server --format "{{.ID}}") wearehadock/metrics-server:v0.3.7
    
    - name: Build the Docker image k8s-dns-node-cache
      run: docker build -t k8s-dns-node-cache:1.15.13 . --file k8s-dns-node-cache.Dockerfile
    - name: tag image 
      run: docker tag $(docker images --filter=reference=k8s-dns-node-cache --format "{{.ID}}") wearehadock/k8s-dns-node-cache:1.15.13
   
    - name: Build the Docker image kube-registry-proxy
      run: docker build -t kube-registry-proxy:0.4 . --file kube-registry-proxy.Dockerfile
    - name: tag image 
      run: docker tag $(docker images --filter=reference=kube-registry-proxy --format "{{.ID}}") wearehadock/kube-registry-proxy:0.4
     
    - name: Build the Docker image addon-resizer
      run: docker build -t addon-resizer:1.8.11 . --file addon-resizer.Dockerfile
    - name: tag image 
      run: docker tag $(docker images --filter=reference=addon-resizer --format "{{.ID}}") wearehadock/addon-resizer:1.8.11
      
    - name: Build the Docker image pause
      run: docker build -t pause:3.2 . --file pause.Dockerfile
    - name: tag image 
      run: docker tag $(docker images --filter=reference=pause --format "{{.ID}}") wearehadock/pause:3.2
      
      
    - name: Docker Login
      env:
        DOCKER_USER: 'wearehadock'
        DOCKER_PASS: ${{ secrets.PASS_DOCKERHUB }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      
    - name: push kube-proxy
      run: docker push wearehadock/kube-proxy:v1.18.10
        
    - name: push metrics-server
      run: docker push wearehadock/metrics-server:v0.3.7
   
    - name: push k8s-dns-node-cache image
      run: docker push wearehadock/k8s-dns-node-cache:1.15.13
        
    - name: push kube-registry-proxy image
      run: docker push wearehadock/kube-registry-proxy:0.4
    
    - name: push addon-resizer image
      run: docker push wearehadock/addon-resizer:1.8.11
    
    - name: push pause image
      run: docker push wearehadock/pause:3.2
